//! A sorted list of character mappings.
//!
//! Automatically generated by contrib/gen_case_fold.py.

// Any manual changes will be lost.


use crate::stringprep::mapping::{Mapping, MappingTarget};


/// The mapping.
pub(crate) const MAPPING: [Mapping; 29] = [
    Mapping::new('\u{00}', '\u{08}', MappingTarget::ThrowAway),
    Mapping::new('\u{09}', '\u{0D}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{0E}', '\u{1F}', MappingTarget::ThrowAway),
    Mapping::new('\u{7F}', '\u{84}', MappingTarget::ThrowAway),
    Mapping::new('\u{85}', '\u{85}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{86}', '\u{9F}', MappingTarget::ThrowAway),
    Mapping::new('\u{A0}', '\u{A0}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{AD}', '\u{AD}', MappingTarget::ThrowAway),
    Mapping::new('\u{34F}', '\u{34F}', MappingTarget::ThrowAway),
    Mapping::new('\u{6DD}', '\u{6DD}', MappingTarget::ThrowAway),
    Mapping::new('\u{70F}', '\u{70F}', MappingTarget::ThrowAway),
    Mapping::new('\u{1680}', '\u{1680}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{1806}', '\u{1806}', MappingTarget::ThrowAway),
    Mapping::new('\u{180B}', '\u{180E}', MappingTarget::ThrowAway),
    Mapping::new('\u{2000}', '\u{200A}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{200B}', '\u{200F}', MappingTarget::ThrowAway),
    Mapping::new('\u{2028}', '\u{2029}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{202A}', '\u{202E}', MappingTarget::ThrowAway),
    Mapping::new('\u{202F}', '\u{202F}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{205F}', '\u{205F}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{2060}', '\u{2063}', MappingTarget::ThrowAway),
    Mapping::new('\u{206A}', '\u{206F}', MappingTarget::ThrowAway),
    Mapping::new('\u{3000}', '\u{3000}', MappingTarget::One('\u{20}')),
    Mapping::new('\u{FE00}', '\u{FE0F}', MappingTarget::ThrowAway),
    Mapping::new('\u{FEFF}', '\u{FEFF}', MappingTarget::ThrowAway),
    Mapping::new('\u{FFF9}', '\u{FFFC}', MappingTarget::ThrowAway),
    Mapping::new('\u{1D173}', '\u{1D17A}', MappingTarget::ThrowAway),
    Mapping::new('\u{E0001}', '\u{E0001}', MappingTarget::ThrowAway),
    Mapping::new('\u{E0020}', '\u{E007F}', MappingTarget::ThrowAway),
];
